version: '3'
services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - type: bind
        source: ./mongodata
        target: /data/db

  keycloak:
    container_name: keycloak
    image: duzhinsky/chess:keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080"


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    external_links:
      - main
      - wsserver
      - keycloak