version: '3'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "80:8080"
    environment:
      spring_profiles_active: docker
      MONGO_URL: mongodb://user:pass@mongodb
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: chess
    volumes:
      - type: bind
        source: ./mongodata
        target: /data/db