name: Backend PR test

on:
  pull_request:
    paths:
      - 'api/**'
      - '!api/gradlew'
      - '!api/gradle/**'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        working-directory: ./api
        run: ./gradlew test