name: Build java backend

on:
  pull_request:
    paths:
      - 'api/**'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          path: 'api'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Pwd
        run: pwd
      - name: ls
        run: ls -al
      - run: cd api/
      - name: Execute Gradle build
        run: ./gradlew build