name: Publish main image

on:
  push:
    branches:
      - master
    paths:
      - 'api/main/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        working-directory: ./api/
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chess-main:prod . -f ./main/Dockerfile
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chess-main:prod